[workspace.package]
authors = ["Wei Tang <wei@pacna.org>"]
license = "Apache-2.0"
edition = "2021"
repository = "https://github.com/rust-blockchain/blockchain"

[workspace]
resolver = "2"
members = [
	"blockchain",
	"blocknet",
	"tinyjam",
]
